### PR TITLE
Added `range`.

### PR DESCRIPTION
**Pull request by taphu**
See commits for comments.

### CODE REVIEW

**Comment by potomak** [comment]
In general I'd like for eureka-semver to accept expression like `>= 0.5 && < 0.6`.

**Comment by glasserc** [comment]
How is this different from the ``versionInRangeP`` from ``Network.Eureka.Version.Cabal`` ?

**Comment by taphu** [comment]
@glasserc It is not different, unless @potomak means to say he actually wants to parse a string expression.

**Comment by taphu** [comment]
One thing I think about the `Network.Eureka.Version.Cabal` module is that it shouldn't exist. There are exactly zero things in it related to Cabal.

**Comment by glasserc** [comment]
@taphu Thanks -- my question wasn't directed towards @potomak but whoever wrote the ``range`` function.

**Comment by potomak** [comment]
@taphu @glasserc take a look at https://github.com/SumAll/haskell-eureka-semver/pull/13, a third way of defining version ranges...

**Pull request merged**
